### ISSUE TITLE
Please update to version >= 2.47 from sourceforge

### ISSUE THREAD

**Issue by t-brink** [bcoe/imaplib2#19]
Hi! Could you please update this mirror to the newest version from sourceforge? It contains some Python 3 related fixes and your repository seems to be somewhat more discoverable due to being on PyPI.

Thanks for your work!

**Comment by graingert** [comment]
I'll get around to it soon, but you can send a pull request if you like :)

**Comment by achernet** [comment]
I just submitted a PR for v2.52.0 - that looks like the latest version as of today.

**Comment by timpeoples** [comment]
...and a new push to PyPI would be awesome too... S'il vous plait  :D

**Comment by tcyrus** [comment]
:+1: for PyPi push
