### ISSUE TITLE
Fix import paths

### ISSUE THREAD

**Issue by tcyrus** [bcoe/imaplib2#22]
Right now if I want to use `imaplib2` instead of doing this:

``` py
from imaplib2 import IMAP4_SSL
M = IMAP4_SSL('imap.gmail.com')
```

I have to do this:

``` py
from imaplib2 import imaplib2
M = imaplib2.IMAP4_SSL('imap.gmail.com')
```

I believe this should be fixed because `imaplib2` is supposed to be a drop-in replacement for `imaplib`

**Comment by ankostis** [comment]
+1 for @tcyrus 
@bcoe it it just a matter of dropping package `imaplib2.__init__.py` and moving `imaplib2/imaplib2.py` to the root of your project.

I can PR if you want.
