### ISSUE TITLE
Please upload tests to PyPI

### ISSUE THREAD

**Issue by dotlambda** [bcoe/imaplib2#28]
Title says it all...

**Comment by graingert** [comment]
Tests shouldn't be uploaded to PyPI

**Comment by dotlambda** [comment]
Well, they don't harm on there. And this makes it possible for distributions to incorporate tests in their build systemd.
But if you're against uploading tests, would you mind tagging releases on GitHub?

**Comment by graingert** [comment]
We've moved to https://github.com/imaplib2/imaplib2
