### ISSUE TITLE
Make a new release into PyPi

### ISSUE THREAD

**Issue by frabcus** [bcoe/imaplib2#6]
Can you bump the version and make a new release into PyPi?

This is to make the Python 3 compatibility (https://github.com/bcoe/imaplib2/pull/4/files) code in an official version!

**Comment by bcoe** [comment]
Hey @frabcus, master should be up on PyPi:

https://pypi.python.org/pypi/imaplib2/2.37.4

Let me know if you run into issues.

**Comment by frabcus** [comment]
At at least installs and imports for me, thank you!
