### ISSUE TITLE
AttributeError caused by queue.get_nowait() not raising queue.Empty

### ISSUE THREAD

**Issue by mbmccoy** [bcoe/imaplib2#9]
There is a documented queue "feature" that caused me some intermittent problems.

Under certain situations, "there may be an infinitesimal delay before the queue’s empty() method returns False and get_nowait() can return without raising queue.Empty" (see the second note [here](https://docs.python.org/3.4/library/multiprocessing.html#pipes-and-queues)). This "feature" occaisionally causes an AttributeError to be raised on line 1728 because `get_nowait()` returns `None` (which clearly doesn't have an `abort()` method).

One workaround is to just catch the AttributeError and `break`, but this leaves the loop with `self.ouq.empty() == True`. I suspect that the correct solution is to catch the AttributeError and `pass` until `ouq.empty()` starts returning `False`, that is:

        # Line 1725 here
        while not self.ouq.empty():
            try:
                self.ouq.get_nowait().abort(typ, val)
            except queue.Empty:
                break
            except AttributeError:
                # See notes at https://docs.python.org/3.4/library/multiprocessing.html#pipes-and-queues
                pass  # Soon enough, self.ouq.empty() should become True
        self.ouq.put(None)

Of course, this route risks a hang if the "infinitesimal delay" is not, in fact, infinitesimal. If that's the case, a `break` may be more appropriate. Thoughts?

**Comment by bcoe** [comment]
@mbmccoy this is a mirror of Imaplib2 I've been using to publish to PyPi for a few years, any issues should be opened against the project itself:

 http://sourceforge.net/projects/imaplib2/
